import './scripts/actions/ability-test.mjs';
import './scripts/actions/audio.mjs';
import { registerBondsmithActions } from './scripts/actions/bondsmith.mjs';
import { registerCalendariaActions } from './scripts/actions/calendaria.mjs';
import { registerDnd5eActions } from './scripts/actions/dnd5e.mjs';
import { registerDontForgetActions } from './scripts/actions/dont-forget.mjs';
import { registerHeroMancerActions } from './scripts/actions/hero-mancer.mjs';
import { registerIntegrationActions } from './scripts/actions/integrations.mjs';
import './scripts/actions/messaging.mjs';
import { registerMindfulEncountersActions } from './scripts/actions/mindful-encounters.mjs';
import { registerMinstrelActions } from './scripts/actions/minstrel.mjs';
import { registerPeddlerActions } from './scripts/actions/peddler.mjs';
import { registerPf2eActions } from './scripts/actions/pf2e.mjs';
import './scripts/actions/scene.mjs';
import './scripts/actions/skill-test.mjs';
import { registerSpellBookActions } from './scripts/actions/spell-book.mjs';
import { registerTenacityActions } from './scripts/actions/tenacity.mjs';
import './scripts/actions/tile.mjs';
import { registerTokenLightConditionActions } from './scripts/actions/token-light-condition.mjs';
import './scripts/actions/token.mjs';
import './scripts/actions/variables.mjs';
import { registerVgmusicActions } from './scripts/actions/vgmusic.mjs';
import { createApi } from './scripts/api.mjs';
import { registerTriggerSheet } from './scripts/apps/trigger-config.mjs';
import { MODULE } from './scripts/constants.mjs';
import { registerTriggerBehavior } from './scripts/data/trigger-behavior.mjs';
import { registerMattImportContextMenu } from './scripts/import/matt-scene-menu.mjs';
import { registerBondsmithIntegration } from './scripts/integrations/bondsmith.mjs';
import { registerCalendariaIntegration } from './scripts/integrations/calendaria.mjs';
import { registerHeroMancerIntegration } from './scripts/integrations/hero-mancer.mjs';
import { registerPeddlerIntegration } from './scripts/integrations/peddler.mjs';
import { registerPseudoEvents } from './scripts/pseudo-events.mjs';
import { registerQuickCreate } from './scripts/quick-create.mjs';
import { registerRecipesButton } from './scripts/recipes.mjs';
import { registerReferenceRemap } from './scripts/reference-remap.mjs';
import { registerTileLink } from './scripts/tile-link.mjs';
import { registerTriggerLinkEnricher } from './scripts/trigger-link-enricher.mjs';
import './styles/glyph.css';

Hooks.once('init', () => {
  ATLAS.register(MODULE.ID, { title: MODULE.NAME, github: 'Sayshal/glyph', theme: { scope: '.glyph' } });
  registerTriggerBehavior();
  registerTriggerSheet();
  registerPseudoEvents();
  registerTileLink();
  registerReferenceRemap();
  registerRecipesButton();
  registerMattImportContextMenu();
  registerQuickCreate();
  registerTriggerLinkEnricher();
  registerDnd5eActions();
  registerPf2eActions();
  registerIntegrationActions();
  registerTenacityActions();
  registerPeddlerActions();
  registerDontForgetActions();
  registerHeroMancerIntegration();
  registerCalendariaIntegration();
  registerCalendariaActions();
  registerHeroMancerActions();
  registerBondsmithActions();
  registerSpellBookActions();
  registerMinstrelActions();
  registerTokenLightConditionActions();
  registerMindfulEncountersActions();
  registerVgmusicActions();
});

Hooks.once('ready', () => {
  createApi();
  Hooks.callAll(MODULE.HOOKS.READY, game.modules.get(MODULE.ID).api);
  setTimeout(() => {
    registerBondsmithIntegration();
    registerPeddlerIntegration();
  }, 0);
  ATLAS.log(3, 'Glyph ready.');
});
